import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const ptSans = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "MediSwift",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ptSans.className} cz-shortcut-listen="true">
          {children}
          <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}